---
# General Settings
format: html
echo: false
warning: false

# Theme Settings
theme: default
barposition: top
footer-left: "Made with [surveydown](https://surveydown.org)"
footer-right: '[<i class="bi bi-github"></i> Source Code](https://github.com/surveydown-dev/templates)'

# Survey Settings
use-cookies: false
auto-scroll: false
rate-survey: false
system-language: en
highlight-unanswered: true
highlight-color: blue
capture-metadata: true
all-questions-required: false
---

```{r}
library(surveydown)
```

::: {.sd_page id=welcome}

# Template - Predefined Random Options

Here is a basic "multiple choice" question where the options are randomly sampled from 1 to 100. The random samples are grabbed from a **predefined** csv file. If you refresh the page, the options should change.

```{r}
sd_output("q1", type = "question")
sd_next()
```

:::

::: {.sd_page id=page2}

This is another page in your survey.
```{r}
sd_next()
```

:::

::: {.sd_page id=end}

This it the last page in the survey

```{r}
sd_close()
```

:::
